### PR TITLE
Change microblocks origin.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by hobinjk** [comment]
What are the changes to gpio-adapter and thing-url-adapter?

**Comment by mrstegeman** [comment]
It was just from running `git submodule update --init`. It's irrelevant, as the builder script does the same thing. I just wanted to make sure nothing else needed to change for this submodule.

**Comment by dhylands** [comment]
Actually, the script does `git submodule update --init --remote` which basically ignores the local submodule hash and pulls in the latest hash from the remote. If you run without --remote, it may very well take your local respository back in time (to whatever the hash that's currently recorded in this repo is).

**Comment by mrstegeman** [comment]
@dhylands I had a typo, I did run with `--remote`.

**Pull request merged**
