### PR TITLE
generic-sensors-adapter skip darwin os

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: I4b696ab56d03616d9b0ec1015a94e595d890f207
Signed-off-by: Philippe Coval <rzr@users.sf.net>

### CODE REVIEW

**Comment by mrstegeman** [comment]
For testing, you can remove everything from the ADAPTERS array except yours. That way you don't get failures due to enocean.

**Comment by rzr** [comment]
good idea

**Comment by rzr** [comment]
Please first merge
https://github.com/mozilla-iot/addon-builder/pull/44

**Comment by mrstegeman** [comment]
Ok, merged. Rebase?

**Comment by rzr** [comment]
Yes it's same, now I'll have to update activity adapter...

May a bug be open for enocean adapter and assigned to maintainer ?

**Comment by mrstegeman** [comment]
Already working on it: https://github.com/mozilla-iot/addon-list/pull/639

**Comment by mrstegeman** [comment]
We'll use the builder for your next release of generic-sensors-adapter and keep the current builds for this version.

**Pull request closed without merging**
