### PR TITLE
Alias gtar to tar to support mtime

### PR DESCRIPTION
**Pull request by hobinjk**
Fix https://github.com/mozilla-iot/gpio-adapter/issues/20

### CODE REVIEW

**Comment by hobinjk** [comment]
(it's not actually `alias` because that doesn't work across shells)

**Comment by hobinjk** [comment]
Hmm, looks like travis's osx environment doesn't have gtar installed, this could get fun.

**Comment by mrstegeman** [comment]
Can you just install homebrew and pull in gtar?

https://brew.sh/

**Comment by hobinjk** [comment]
Yes, that's where my gtar is from. I'll add the install and see if it works (nicely enough travis has homebrew pre-installed)

**Pull request merged**
